--- #YAML:1.0
name:                PDF-Create
version:             1.05
abstract:            create PDF files
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
